also catch IllegalArgumentException which is caused with a url like this:
http://www.foo.l:8080/site/shoots.jsp?c=1&(.*?(\(.*?\))?[^(]*?)

and comes across as:

java.lang.IllegalArgumentException: Invalid mapped property '('


git-svn-id: http://tagonist.tigris.org/svn/tagonist/trunk@35 c92c706e-b2fa-0310-a644-dfea2ba336d8