a query string of this: )(.*?)%5C4%20*%5C%5D/,/%5E(:)(%5B%5Cw-%5D+)%5C(
caused: 

java.lang.StringIndexOutOfBoundsException: String index out of range: -10
at java.lang.String.substring(String.java:1938)
at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:908)
at org.tagonist.beanutils.ErrorTrappingBeanUtilsBean.populate(ErrorTrappingBeanUtilsBean.java:126)

git-svn-id: http://tagonist.tigris.org/svn/tagonist/trunk@36 c92c706e-b2fa-0310-a644-dfea2ba336d8